apiVersion: v1
kind: Secret
metadata:
  name: image-pull-creds
  namespace: api-portal
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "e30K"

---
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-creds
  namespace: tap-gui
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "e30K"

---
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-creds
  namespace: app-live-view
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "e30K"