---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: package-installs
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 2m
  path: flux/packages/clusters/${cluster_name}
  prune: true
  postBuild:
    substitute:
      cluster_name: ${cluster_name}
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: infra-base