apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca
spec:
  acme:
    privateKeySecretRef:
      name: step-ca-key-avi
    solvers:
    - http01:
        ingress:
          ingressClassName: avi-lb
