apiVersion: v1
kind: Secret
metadata:
  name: image-pull-creds
  namespace: api-auto-registration
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "e30K"