apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: smallstep
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 5m0s
  url: https://smallstep.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: step-ca
  namespace: tanzu-continuousdelivery-resources
spec:
  releaseName: step-ca
  targetNamespace: step-ca
  interval: 10m
  chart:
    spec:
      chart: step-certificates
      version: 1.26.0
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: tanzu-continuousdelivery-resources
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              name: step-ca-step-certificates
            patch: |
              - op: add
                path: /spec/loadBalancerClass
                value: ako.vmware.com/avi-lb
  values:
    image:
      repository: harbor-repo.vmware.com/dockerhub-proxy-cache/smallstep/step-ca
    bootstrap:
      image:
        repository: harbor-repo.vmware.com/dockerhub-proxy-cache/smallstep/step-ca-bootstrap
      secrets: false
      enabled: false
      configmaps: false
    existingSecrets:
      enabled: true
      ca: true
      certsAsSecret: true
      configAsSecret: true
    inject:
      enabled: false
    service:
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: step-ca.tap-vcf.h2o-4-20916.h2o.vmware.com
