apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: smallstep
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 5m0s
  url: https://smallstep.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: step-ca
  namespace: tanzu-continuousdelivery-resources
spec:
  releaseName: step-ca
  targetNamespace: step-ca
  interval: 10m
  chart:
    spec:
      chart: step-certificates
      version: 1.11.3
      sourceRef:
        kind: HelmRepository
        name: smallstep
        namespace: tanzu-continuousdelivery-resources
  values: