apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-man-deliverable-role
rules:
- apiGroups: [
    "cert-manager.io"
    ]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-ns-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-man-deliverable-role
subjects:
- kind: ServiceAccount
  name: default