apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca
spec:
  acme:
    server: ${server_url}
    email: ${email}
    caBundle: ${ca_bundle}
    privateKeySecretRef:
      name: step-ca-key
    solvers:
    - http01:
        ingress:
          ingressClassName: contour
          podTemplate:
            spec:
              imagePullSecrets:
              - name: api-portal-image-pull-secret
